[system]
# 是否显示托盘图标
show_tray_icon = true
# 是否开机启动
start_at_login = false
# 日志级别
logging_level = "info"
# 历史记录过期时间/d
history_ttl = 1000

[ui_automation]
# 窗口元素收集间隔/ms
collect_interval = 10
# 忽略应用
ignore_apps = [
    "Cursor.exe",
    "Code.exe",
    "Trae.exe",
]
# 默认编辑控件类型
default_edit_control_types = [50004]
# 此控件类型包含文本内容时视为编辑控件
hastext_edit_control_types = [50026]

# 特殊应用的额外编辑控件类型
[ui_automation.app_edit_control_types]
"WINWORD.EXE" = [
    50029,
    50033,
]
"EXCEL.EXE" = [
    50029,
    50033,
]
"msedge.exe" = [50003]

[keyboard]
# 修饰键按下时, 不监听任何键盘按键
propagation_modifier = [
    "LCtrl",
    "RCtrl",
    "LAlt",
    "RAlt",
    "LWin",
    "RWin",
    "LShift",
    "RShift",
]

# 可用键盘按键, 包括0-9a-z,./;'[]\-=`
[keyboard.available_key]
Backspace = 8
CapsLock = 20
Delete = 46
Down = 40
End = 35
Enter = 13
Esc = 27
F1 = 112
F10 = 121
F11 = 122
F12 = 123
F2 = 113
F3 = 114
F4 = 115
F5 = 116
F6 = 117
F7 = 118
F8 = 119
F9 = 120
Home = 36
Insert = 45
LAlt = 164
LCtrl = 162
LShift = 160
LWin = 91
Left = 37
Num0 = 96
Num1 = 97
Num2 = 98
Num3 = 99
Num4 = 100
Num5 = 101
Num6 = 102
Num7 = 103
Num8 = 104
Num9 = 105
NumAdd = 107
NumDecimal = 110
NumDivide = 111
NumMultiply = 106
NumSubtract = 109
PageDown = 34
PageUp = 33
RAlt = 165
RCtrl = 163
RShift = 161
RWin = 92
Right = 39
Space = 32
Tab = 9
Up = 38

[ai_client]
# AI provider type: "API" or "CMD"
provider = "API"
# For "API" provider
api_key = ""
api_url = "https://ark.cn-beijing.volces.com/api/v3/chat/completions"
api_model = "deepseek-v3-250324"
# For "CMD" provider
cmd = "C:\\Users\\sinph\\scoop\\apps\\nodejs\\current\\bin\\gemini.cmd -m gemini-2.5-flash -p"
# 完整提示词, 可用变量: app_name, window_title, window_handle, input_title, input_handle, input_content, input_history, clipboard_contents
prompt = """
Your task is to complete the content in the input box of the {{app_name}} application window. The window has a title of "{{window_title}}" and a handle of "{{window_handle}}". The input box has a title of "{{input_title}}" and a handle of "{{input_handle}}".
First, please carefully read the following context information which includes input history and clipboard content.
<ContextInfo>
<InputHistory>
{{input_history}}
</InputHistory>
<ClipboardContent>
{{clipboard_contents}}
</ClipboardContent>
</ContextInfo>
Now, here is the current content in the input box:
<InputBoxContent>
{{input_content}}
</InputBoxContent>
Here are some examples of how the completion should be formatted:
<Examples>
<Example>
<InputBoxContent>不知</InputBoxContent>
<Completion>道</Completion>
</Example>
<Example>
<InputBoxContent>hello wo</InputBoxContent>
<Completion>rld</Completion>
</Example>
<Example>
<InputBoxContent>Attention i</InputBoxContent>
<Completion>s all you need</Completion>
</Example>
<Example>
<InputBoxContent></InputBoxContent>
<Completion>收到</Completion>
</Example>
</Examples>
Your output should only be the completion of the input box content.
"""

[keybinding]
# 退出候选
exit_overlay = ["Esc"]
# 接受候选
accept_candidate = ["Tab"]
# 选择候选的第一个字符
select_candidate_char_1 = ["1"]
# 选择候选的第二个字符
select_candidate_char_2 = []
select_candidate_char_3 = []
select_candidate_char_4 = []
select_candidate_char_5 = []
select_candidate_char_6 = []
select_candidate_char_7 = []
select_candidate_char_8 = []
select_candidate_char_9 = []

[privacy]
# 是否启用隐私保护
enable = true
# 隐私保护规则, 过滤手机号, 身份证号, IP, 常见API Key
rules = ["(1[3-9]\\d{9})|(\b\\d{17}[\\dXx]\b)|(\b(?:\\d{1,3}\\.){3}\\d{1,3}\b)|(sk-[a-zA-Z0-9]{20,})"]

[overlay]
# 候选框刷新间隔/ms
refresh_interval = 50
# 候选框相对位置/px
relative_x = 0
relative_y = -28
# 候选框样式
style = """
{
  font-size: 1em;
  font-family: 'Segoe UI', 'PingFang SC', 'Microsoft YaHei', sans-serif;
  margin: 0;
  padding: 2px 4px;
  background: rgba(255, 255, 255, 0.92);
  color: #222;
  border-radius: 6px;
  box-shadow: 0 4px 24px rgba(0,0,0,0.18), 0 1.5px 4px rgba(0,0,0,0.12);
  border: 1px solid rgba(0,0,0,0.06);
  backdrop-filter: blur(8px);
  transition: box-shadow 0.2s, background 0.2s;
}
"""
